### PR TITLE
Add dotenv to store clientside keys

### PR DESCRIPTION
**Pull request by patrickkim**
use `process.env[’SECRET KEY FROM ENV’]` to use secret

### CODE REVIEW

**Comment by j-clark** [comment]
out curiosity, what's this going to be used for — as in what keys does the RCL need?

**Comment by patrickkim** [comment]
I figure it would be useful to add a Google Maps API so that you can preview a map component. I'm open to other suggestions.

**Comment by drewdrewthis** [comment]
@patrickkim LGTM if you think we'll use it.

**Comment by patrickkim** [comment]
Don't need this after all. The consumer should handle their respective api keys.

**Pull request closed without merging**
