### PR TITLE
Simplify stepProgress code.

### PR DESCRIPTION
**Pull request by patrickkim**
Get some CR 👀 @cisacke @drewdrewthis

### CODE REVIEW

**Comment by cisacke** [comment]
@patrickkim  ^^

**Comment by drewdrewthis** [comment]
@cisacke @patrickkim In the styles, `pointer-events` is set to `none` -- I believe that we actually don't want to give the user that ability.. you can check with Jason Fromm though, he's the Renter's PM. We can probably handle this issue in another ticket/PR though

**Comment by patrickkim** [comment]
Carry over from the old styles. I'm going to remove them. We'll see if we need this in the future.

**Comment by patrickkim** [comment]
currently its a `href` but show me a use case in where it needs to change and it will be done.

**Pull request merged**
